### ISSUE TITLE
resolve 'node:process' module error

### ISSUE THREAD

**Issue by 2214962083** [antfu/esno#13]
when i try run a ts file that devDependencies with ora module

esno throw a error can not find module 'node:process'

see [ora module](https://github.com/sindresorhus/ora/blob/8364664d579f806ef65d259f5fe99c4bc82ffa5b/index.js#L1)

**Comment by hyrious** [comment]
Maybe it's because `require("node:process")` does not work on your node engine (node16 is ok).
