### ISSUE TITLE
Restart server on file changes

### ISSUE THREAD

**Issue by nshusr** [antfu/esno#14]
Has anyone set this up to listen to file changes and restart the node process on a file change? https://github.com/egoist/esbuild-register/issues/30

**Comment by taylor-knapp** [comment]
You can combine this with nodemon pretty easily to achieve hot reloading:

The following package.json excerpt uses `esmo` for an es module build.

```json
  "type": "module",
  "scripts": {
    "start": "nodemon index.ts"
  },
  "nodemonConfig": {
    "exec": "esmo",
    "ext": "js,json,ts"
  },
  "devDependencies": {
    "esno": "^0.13.0",
    "nodemon": "^2.0.15",
    "typescript": "^4.5.4"
  }
```
