### ISSUE TITLE
ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time

### ISSUE THREAD

**Issue by naknode** [antfu/esno#21]
Node.js: `14.16.1`
NPM: `6.14.12`

`package.json`:
```json
{
  "type": "module",
  "scripts": {
    "start": "esmo index.ts"
  },
  "dependencies": {
    "esno": "*"
  },
  "devDependencies": {
    "playwright": "^1.17.1"
  }
}
```

`index.ts`:

```typescript
console.log("Hello world.");
```

```
~/project/docgen
❯ npm run start

> @ start /Users/UsernameHere/project/docgen
> esmo index.ts

(node:60266) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Hello world
```

What am I doing wrong to get this experimental message? I am on MacOS Big Sur 11.6.1

**Comment by antfu** [comment]
This is expected since the esm loader is not finalized yet.

**Comment by naknode** [comment]
@antfu I thought this was suppose to make Node.js utilize/run TypeScript out-of-the-box? Shouldn't `esmo` run a simple `.ts` file with a `console.log` or am I missing the point? Apologies as I'm not too well versed in the intricacies of build tools.

**Comment by antfu** [comment]
What do you mean? It's from Node, not us.
https://nodejs.org/api/esm.html#loaders
