### ISSUE TITLE
esno fails to parse optional chaining inside jsx/tsx files

### ISSUE THREAD

**Issue by CyriacBr** [antfu/esno#3]
### Bug reproduction
foo.tsx:
```ts
import React from 'react';

const myComp: React.FC = () => {
  function fooBar() {}
  console.log(fooBar?.());
  return <div></div>;
};
```

`esno foo.tsx`

stacktrace:
```bash
  console.log(fooBar?.());
                     ^

SyntaxError: Invalid or unexpected token
    at Object._compile (/home/cyriac/.nvm/versions/node/v14.0.0/lib/node_modules/esno/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
child_process.js:650
    throw err;
```

Strangely enough, this works on plain `js` and `ts` files, but not `j/tsx`.
This error seems to come from `pirates` but figured I'd get more luck asking here as `pirtates` doesn't seem maintained anymore.

**Comment by antfu** [comment]
Do you upgrade to the latest `esno`? What's your `target` in `tsconfig.json`? Can you share a minimal reproduce repo? Thanks.
