### ISSUE TITLE
esmo not work

### ISSUE THREAD

**Issue by yyyang1996** [antfu/esno#7]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /xxx/esbuild-node-loader/package.json

![Xnip2021-06-07_19-11-56](https://user-images.githubusercontent.com/34713301/121007084-3b756980-c7c4-11eb-9731-cbf7216c6507.jpg)

**Comment by thelinuxlich** [comment]
Same problem!

**Comment by radudiaconu0** [comment]
Same problem here

**Comment by antfu** [comment]
Should be fixed in v0.7.1
